### ISSUE TITLE
Overriding context values when validation fails

### ISSUE THREAD

**Issue by mengqing** [michaelherold/interactor-contracts#13]
Currently when a validation fails, the error message is set on the context value, overriding the original value. This is fine in my opinion if you're only checking for the presence of the value. However when you're checking for anything else, you lose the original context value and it is also difficult to identify which part of the schema is giving errors.

## Current Behaviour
```
class Foobar
  include Interactor
  include Interactor::Contracts

  expects do
    required(:foobar).value(gt?: 10)
  end
end

Foobar.call(foobar: 1)
=> #<Interactor::Context foobar=["foobar must be greater than 10"]>
```

## Proposed Behaviour
```
class Foobar
  include Interactor
  include Interactor::Contracts

  expects do
    required(:foobar).value(gt?: 10)
  end
end

Foobar.call(foobar: 1)
=> #<Interactor::Context foobar=1 errors={:foobar=>["foobar must be greater than 10"]}>
```

Let me know what you think, and am happy to submit a PR

**Comment by mengqing** [comment]
I ended up implementing this feature because we need this functionality. I'll submit a PR and see if it makes sense or requires any improvements

**Comment by kartikluke** [comment]
Isn't this just because the default consequence is set up to be `context.fail!(breaches)`? All you would have to do is set `on_breach` to do what you wanted. In this case.

```
on_breach do |breaches|
  context.fail!(errors: breaches)
end
```

If this is more sensible it could become the new default.

**Comment by michaelherold** [comment]
That sounds reasonable to me. It goes against the original design of the gem, but I can see how it would be useful.

Feel free to submit a PR with the change if you'd like!
