### ISSUE TITLE
easily grab expects or assures breach

### ISSUE THREAD

**Issue by zacheryph** [michaelherold/interactor-contracts#14]
`on_breach` gives you a `BreachSet`. However there is no easy way of knowing whether the contract breach is due to an expectation failure or assurance failure. It'd be handy if the `BreachSet` had a.. location or type or expectation? assurance? methods to be able to tell which contract obligation was breached.

**Comment by zacheryph** [comment]
I suppose... none of the above at this point :x I am just getting started with interactor and contracts and it seemed like it'd be a nice thing to have but yeah, your interactor should most likely fail (before) if the assurance is going to fail and if not your tests should most certainly catch it.

**Comment by michaelherold** [comment]
If you run into a situation where you find you need it, please feel free to reopen and we can discuss it further.
